In [24]:
import pandas as pd

from IPython.display import display


# Series
[2, 4, 6, 8]

s = pd.Series([6, 9, 33])
print(s)

s2 = pd.Series(('Ade', 'Bimbo', 'Charles'), index=['a', 'b', 'c'])
print(s2)

s2['b']

0     6
1     9
2    33
dtype: int64
a        Ade
b      Bimbo
c    Charles
dtype: str

'Bimbo'

In [3]:
dict_data = {
    'Abdul': 19,
    'Giwa': 21
}

ser = pd.Series(dict_data)
ser['Abdul']

np.int64(19)

In [ ]:
s = pd.Series(100, index=list(range(4)))

s

0    100
1    100
2    100
3    100
dtype: int64

In [ ]:
# Create a Series containing:
# 50, 60, 70, 80
#  using indexes:
# Math, English, Physics, Chemistry

In [5]:
# Dataframes
data = {
    "Name": ["John", "Mary", "Steve"],
    "Age": [18, 17, 19],
    "Score": [85, 92, 76]
}

df = pd.DataFrame(data)

print(df)
display(df)

df.iloc[0]
# df.Score[1]
# df['Score'][1]
df['Score']

    Name  Age  Score
0   John   18     85
1   Mary   17     92
2  Steve   19     76

    Name  Age  Score
0   John   18     85
1   Mary   17     92
2  Steve   19     76

0    85
1    92
2    76
Name: Score, dtype: int64

In [ ]:
data = {
    "Richard": [
        ["M", "M"],
        ["Emy", "F"],
        ["Adam", "M"],
    ]
}

df = pd.DataFrame(data, columns=['Name', 'Gender'])

df['Name'][0]

'Richard'

In [36]:
_products = [
    {"id": 1, "name": "Laptop", "price": 1500.00, "color": 4281089616},
    {"id": 2, "name": "Smartphone", "price": 950.99, "color": 4281637083},
    {"id": 3, "name": "Tablet", "price": 599.99, "color": 4280193279},
    {"id": 4, "name": "Headphones", "price": 299.99, "color": 4293348412},
    {"id": 5, "name": "Smart Watch", "price": 399.99, "color": 4294928820},
]

products_data = {
    'id': [],
    'name': [],
    'price': []
}

for p in _products:
    products_data["id"].append(p["id"])
    products_data["name"].append(p["name"])
    products_data["price"].append(p["price"])


display(products_data)
df = pd.DataFrame(products_data)
df

{'id': [1, 2, 3, 4, 5],
 'name': ['Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Smart Watch'],
 'price': [1500.0, 950.99, 599.99, 299.99, 399.99]}

   id         name    price
0   1       Laptop  1500.00
1   2   Smartphone   950.99
2   3       Tablet   599.99
3   4   Headphones   299.99
4   5  Smart Watch   399.99

In [46]:
df = pd.read_csv('people-100.csv')

df.head(10)
df.tail()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [4]:
import pandas as pd

# Series

s = pd.Series(['a', 'b', 'c', 'd'])

print(s[3])

d

In [8]:
s = pd.Series(['Ade', 'Bob', 'Charles'], index=['x', 'y', 'z'])

s['y']

'Bob'

In [14]:
dt = {
    'name': 'Jumoke',
    'country': 'Canada',
    'height': 1.4
}

s = pd.Series(dt)

s['height']

1.4

In [16]:
pd.Series(range(5, 30, 5), index=range(5))

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [ ]:
# Dataframes: 2D
from IPython.display import display

pairs = [
    ['Ade', 20],
    ['Badero', 19],
    ['Chide', 21],
    ['Deede', 23],
]

df = pd.DataFrame(pairs, columns=['Name', 'Age'])

display(df)
print("-" * 15)
df['Name']
df.Age

df.iloc[1]['Age']

     Name  Age
0     Ade   20
1  Badero   19
2   Chide   21
3   Deede   23

---------------

Name    Badero
Age         19
Name: 1, dtype: object

In [ ]:
data = {
    "Name": ["John", "Mary", "Steve"],
    "Age": [18, 17, 19],
    "Score": [85, 92, 76]
}

df = pd.DataFrame(data)

df.sort_values('Age', ascending=True, axis=0)
# df[['Name']]

KeyError: 'Age'

In [ ]:
df = pd.read_csv('people-100.csv')

df.describe() #statistical overview of df

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [57]:
# Manipulating data

df = pd.read_csv('sales.csv')

display(df.head(3))
print('-' * 15)


product_price_df = df[['product', 'unit_price']]
display(product_price_df)
product_price_df.describe()
product_price_df.info()

   order_id        date  product  quantity  unit_price  discount_rate
0      1001  2024-01-05   Laptop         2      1200.0           0.10
1      1002  2024-01-08    Mouse        15        25.0           0.05
2      1003  2024-01-12  Monitor         5       350.0           0.15

---------------

       product  unit_price
0       Laptop      1200.0
1        Mouse        25.0
2      Monitor       350.0
3     Keyboard        85.0
4       Laptop      1200.0
5   Headphones       120.0
6    USB Cable         8.0
7      Monitor       350.0
8       Laptop      1200.0
9     Keyboard        85.0
10       Mouse        25.0
11  Headphones       120.0
12     Monitor       350.0
13         NaN      1200.0
14   USB Cable         8.0
15    Keyboard        85.0
16  Headphones       120.0
17       Mouse        25.0
18     Monitor       350.0
19      Laptop      1200.0

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     19 non-null     str
 1   unit_price  20 non-null     float64
dtypes: float64(1), str(1)
memory usage: 452.0 bytes

In [8]:
df = pd.read_csv("sales.csv")

head_df = df.head()
# print(head_df)

df = df[["product", "unit_price", 'quantity', 'discount_rate']]


df['is_expensive'] = df['unit_price'] > df['unit_price'].median()


# display(df.head())
# df['unit_price'] - 100

df['gross_price'] = df['unit_price'] * df['quantity']

# display(df.head())
# print('-' * 15)

df['discounted_price'] = df['gross_price'] - (df['gross_price'] * df['discount_rate'])

df.head()

# high_value_order: one where discounted price IS ABOVE 1000
# is_cheap
#  unit_price < 20
df['high_value_order'] = df['discounted_price'] > 1000
df['is_cheap'] = df['unit_price'] < 20
df


# dicsount_category:
#   No Discount WHERE discount rate == 0
#   Low Discount WHERE discount rate < 5%
#   Medium Discount WHERE rate > 5%
#  High Discount WHERE rate > 10%

# price_tier (based on unit price)
#   Cheap < 20
#   Mid-range 20-200
#  Expensive   > 200

# is_cheap
#  unit_price < 20

,product,unit_price,quantity,discount_rate,is_expensive,gross_price,discounted_price,high_value_order,is_cheap
0,Laptop,1200.0,2,0.10,True,2400.0,2160.00,True,False
1,Mouse,25.0,15,0.05,False,375.0,356.25,False,False
2,Monitor,350.0,5,0.15,True,1750.0,1487.50,True,False
3,Keyboard,85.0,8,0.08,False,680.0,625.60,False,False
4,Laptop,1200.0,3,0.12,True,3600.0,3168.00,True,False
5,Headphones,120.0,20,0.10,False,2400.0,2160.00,True,False
6,USB Cable,8.0,50,0.00,False,400.0,400.00,False,True
7,Monitor,350.0,4,0.20,True,1400.0,1120.00,True,False
8,Laptop,1200.0,1,0.05,True,1200.0,1140.00,True,False
9,Keyboard,85.0,12,0.10,False,1020.0,918.00,False,False
10,Mouse,25.0,25,0.08,False,625.0,575.00,False,False
11,Headphones,120.0,10,0.15,False,1200.0,1020.00,True,False
12,Monitor,350.0,3,0.10,True,1050.0,945.00,False,False
13,Laptop,1200.0,2,0.18,True,2400.0,1968.00,True,False
14,USB Cable,8.0,100,0.05,False,800.0,760.00,False,True
15,Keyboard,85.0,6,0.12,False,510.0,448.80,False,False
16,Headphones,120.0,8,0.20,False,960.0,768.00,False,False
17,Mouse,25.0,30,0.10,False,750.0,675.00,False,False
18,Monitor,350.0,2,0.25,True,700.0,525.00,False,False
19,Laptop,1200.0,4,0.15,True,4800.0,4080.00,True,False

Using the attached CSV file

Derive the following columns from the dataset:

1. Height_m — convert Height_cm to metres.


2. BMI — calculate from height and weight.


3. Weekly_Workout_Minutes — workouts per week × average workout minutes.


4. Weekly_Workout_Hours — convert weekly minutes to hours.

In [4]:
import pandas as pd
from IPython.display import display

df = pd.read_csv('fitness_activity.csv')

# display(df.head())


df['Height_m'] = df['Height_cm'] / 100

df['BMI'] = round((df.Weight_kg / (df.Height_m ** 2)), 2)
df["Weekly_Workout_Minutes"] = df['Workouts_Per_Week'] * df['Avg_Workout_Minutes']
df['Weekly_Workout_Hours'] = round((df['Weekly_Workout_Minutes'] / 60), 2)

# display(df.sample(10))

df.to_csv('fitness_activity_update.csv', index=False)

sorted_bmi_df = df.sort_values('BMI')

sorted_bmi_df.to_excel('fitness_activity-by-BMI.xlsx', index=False)

In [20]:
new_df = df[['BMI', 'Weekly_Workout_Hours']]

new_df.to_csv('fitness_activity_update.csv', index=False)

new_df.to_excel('data.xlsx', index=False)

In [27]:
# Applying arithmetic operations to columns
# add, sub, mul, div

data = {
    "Name": ["John", "Mary", "Steve"],
    "Age": [18, 17, 19],
    "Score": [25, 32, 36]
}

df = pd.DataFrame(data)

df.Score = df.Score.add(10)
# df.Score.sub(5)
# df.Score.mul(5)
# df.Score.div(5)

df

    Name  Age  Score
0   John   18     35
1   Mary   17     42
2  Steve   19     46

In [30]:
products_data = {
    'Name': ['Headphones', 'Shirt'],
    'Qty': [2, 3],
    'Price_$': [250.99, 25.75]
}

df = pd.DataFrame(products_data)

df["Price_₦"] = df['Price_$'].mul(1_390)

df

         Name  Qty  Price_$   Price_₦
0  Headphones    2   250.99  348876.1
1       Shirt    3    25.75   35792.5

In [40]:
s2 = pd.Series(("Bimbo", 'Abraham', 'abraham' ,"Charles"))

display(s2)
display(s2.sort_values(ascending=True))

s2

pd.Series([4, 2, 8, 5, 5, 9, 7]).sort_values(inplace=True)

0      Bimbo
1    Abraham
2    abraham
3    Charles
dtype: str

1    Abraham
0      Bimbo
3    Charles
2    abraham
dtype: str

1    2
0    4
3    5
4    5
6    7
2    8
5    9
dtype: int64

In [41]:
s2 = pd.Series(("Bimbo", "Abraham", "abraham", "Charles"))

display(s2)
display(s2.sort_values(ascending=True, inplace=True))


s2

0      Bimbo
1    Abraham
2    abraham
3    Charles
dtype: str

None

1    Abraham
0      Bimbo
3    Charles
2    abraham
dtype: str

In [48]:
products_data = {
    "Name": ["Headphones", "Shirt", 'Laptop'],
    "Qty": [2, 3, 0],
    "Price_$": [250.99, 25.75, 945.50],
}

df = pd.DataFrame(products_data)

df.sort_values("Price_$")
display(df.sort_values("Qty", inplace=False))

display(df)

         Name  Qty  Price_$
2      Laptop    0   945.50
0  Headphones    2   250.99
1       Shirt    3    25.75

         Name  Qty  Price_$
0  Headphones    2   250.99
1       Shirt    3    25.75
2      Laptop    0   945.50

In [ ]:
# loc vs iloc

In [8]:
# df.truncate
import pandas as pd

products_data = {
    "Name": ["Headphones", "Shirt", "Laptop"],
    "Qty": [2, 3, 0],
    "Price_$": [250.99, 25.75, 945.50],
}

df = pd.read_csv("sales.csv")

# display(df)

df.truncate(before=2, after=5)

# display(df)

   order_id        date     product  quantity  unit_price  discount_rate
2      1003  2024-01-12     Monitor         5       350.0           0.15
3      1004  2024-01-15    Keyboard         8        85.0           0.08
4      1005  2024-01-18      Laptop         3      1200.0           0.12
5      1006  2024-01-22  Headphones        20       120.0           0.10

In [ ]:
df = pd.read_csv('sales.csv')

display(df)

df.loc[]

    order_id        date     product  quantity  unit_price  discount_rate
0       1001  2024-01-05      Laptop         2      1200.0           0.10
1       1002  2024-01-08       Mouse        15        25.0           0.05
2       1003  2024-01-12     Monitor         5       350.0           0.15
3       1004  2024-01-15    Keyboard         8        85.0           0.08
4       1005  2024-01-18      Laptop         3      1200.0           0.12
5       1006  2024-01-22  Headphones        20       120.0           0.10
6       1007  2024-01-25   USB Cable        50         8.0           0.00
7       1008  2024-02-01     Monitor         4       350.0           0.20
8       1009  2024-02-05      Laptop         1      1200.0           0.05
9       1010  2024-02-08    Keyboard        12        85.0           0.10
10      1011  2024-02-12       Mouse        25        25.0           0.08
11      1012  2024-02-15  Headphones        10       120.0           0.15
12      1013  2024-02-18     Monitor         3       350.0           0.10
13      1014  2024-02-22      Laptop         2      1200.0           0.18
14      1015  2024-02-25   USB Cable       100         8.0           0.05
15      1016  2024-03-01    Keyboard         6        85.0           0.12
16      1017  2024-03-05  Headphones         8       120.0           0.20
17      1018  2024-03-08       Mouse        30        25.0           0.10
18      1019  2024-03-12     Monitor         2       350.0           0.25
19      1020  2024-03-15      Laptop         4      1200.0           0.15

KeyError: 'product'

In [54]:
products_data = {
    "Name": ["Headphones", "Shirt", "Laptop"],
    "Qty": [2, 3, 0],
    "Price_$": [250.99, 25.75, 945.50],
}

df = pd.DataFrame(products_data)

display(df)
# display(df.loc['a'])
# # df.loc['a']['Name']
# df.loc['a', 'Name']
# df.iloc[0, 0]

# display(df.loc['b', 'Qty'])
# df.iloc[1, 1]

# df[['Name', 'Qty']]
# df.loc['a':'b']
# df.loc['a':'b', 'Name':'Qty']

# df.iloc[0:, 2]

# df.iloc[1:2, [0, 2]]
# df.iloc[1:, 1:]
df.iloc[0:]

         Name  Qty  Price_$
0  Headphones    2   250.99
1       Shirt    3    25.75
2      Laptop    0   945.50

         Name  Qty  Price_$
0  Headphones    2   250.99
1       Shirt    3    25.75
2      Laptop    0   945.50

In [68]:
df = pd.read_csv('sales.csv')

display(df)

df.isnull()

df['discount_rate'].isnull()

# df.fillna('<NA>')

df['product'] =  df['product'].fillna('<Missing>')

df.fillna(0)

    order_id        date     product  quantity  unit_price  discount_rate
0       1001  2024-01-05      Laptop       NaN      1200.0           0.10
1       1002  2024-01-08       Mouse      15.0        25.0           0.05
2       1003  2024-01-12     Monitor       5.0       350.0           0.15
3       1004  2024-01-15    Keyboard       8.0        85.0           0.08
4       1005  2024-01-18      Laptop       3.0      1200.0           0.12
5       1006  2024-01-22  Headphones      20.0       120.0           0.10
6       1007  2024-01-25   USB Cable      50.0         8.0            NaN
7       1008  2024-02-01     Monitor       4.0       350.0           0.20
8       1009  2024-02-05      Laptop       1.0      1200.0           0.05
9       1010  2024-02-08    Keyboard      12.0        85.0           0.10
10      1011  2024-02-12       Mouse      25.0        25.0           0.08
11      1012  2024-02-15  Headphones      10.0       120.0           0.15
12      1013  2024-02-18         NaN       3.0       350.0           0.10
13      1014  2024-02-22      Laptop       2.0      1200.0           0.18
14      1015  2024-02-25   USB Cable     100.0         8.0           0.05
15      1016  2024-03-01    Keyboard       6.0        85.0           0.12
16      1017  2024-03-05  Headphones       8.0       120.0           0.20
17      1018  2024-03-08       Mouse      30.0        25.0           0.10
18      1019  2024-03-12     Monitor       2.0       350.0           0.25
19      1020  2024-03-15      Laptop       4.0      1200.0           0.15

    order_id        date     product  quantity  unit_price  discount_rate
0       1001  2024-01-05      Laptop       0.0      1200.0           0.10
1       1002  2024-01-08       Mouse      15.0        25.0           0.05
2       1003  2024-01-12     Monitor       5.0       350.0           0.15
3       1004  2024-01-15    Keyboard       8.0        85.0           0.08
4       1005  2024-01-18      Laptop       3.0      1200.0           0.12
5       1006  2024-01-22  Headphones      20.0       120.0           0.10
6       1007  2024-01-25   USB Cable      50.0         8.0           0.00
7       1008  2024-02-01     Monitor       4.0       350.0           0.20
8       1009  2024-02-05      Laptop       1.0      1200.0           0.05
9       1010  2024-02-08    Keyboard      12.0        85.0           0.10
10      1011  2024-02-12       Mouse      25.0        25.0           0.08
11      1012  2024-02-15  Headphones      10.0       120.0           0.15
12      1013  2024-02-18   <Missing>       3.0       350.0           0.10
13      1014  2024-02-22      Laptop       2.0      1200.0           0.18
14      1015  2024-02-25   USB Cable     100.0         8.0           0.05
15      1016  2024-03-01    Keyboard       6.0        85.0           0.12
16      1017  2024-03-05  Headphones       8.0       120.0           0.20
17      1018  2024-03-08       Mouse      30.0        25.0           0.10
18      1019  2024-03-12     Monitor       2.0       350.0           0.25
19      1020  2024-03-15      Laptop       4.0      1200.0           0.15

In [ ]:
df = pd.read_csv("sales.csv")

display(df)

# df.dropna()
df.drop_duplicates()

In [75]:
df = pd.read_csv('people-100.csv')

df = df.head()

df["First Name"] = df["First Name"].str.upper()

df

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
0,1,88F7B33d2bcf9f5,SHELBY,Terrell,Male,elijah57@example.net,001-084-906-7849x73518,1945-10-26,Games developer
1,2,f90cD3E76f1A9b9,PHILLIP,Summers,Female,bethany14@example.com,214.112.6044x4913,1910-03-24,Phytotherapist
2,3,DbeAb8CcdfeFC2c,KRISTINE,Travis,Male,bthompson@example.com,277.609.7938,1992-07-02,Homeopath
3,4,A31Bee3c201ef58,YESENIA,Martinez,Male,kaitlinkaiser@example.com,584.094.6111,2017-08-03,Market researcher
4,5,1bA7A3dc874da3c,LORI,Todd,Male,buchananmanuel@example.net,689-207-3558x7233,1938-12-01,Veterinary surgeon

In [79]:
"abc".replace('ab', 'A')

"   oYIN      is    here   ".strip()

'oYIN      is    here'

In [ ]:
# Data Processing Techniques in Machine Learning

# datasets, training, learning, real-world problem (ML)
# computers behaving like humans (intelligence), reasoning, making decisions

In [25]:
# Data cleaning

import pandas as pd

df = pd.read_csv("student_success.csv")

# print(df.shape)

# df.info()

display(df)
display(df['Hours_attended'].sum())
display(df.isnull()['Gender'].sum())
display(df.isnull().sum())
# df.duplicated()

df["Success_exam"] = df["Success_exam"].str.replace("Yes", "Y")
df["Success_exam"] = df["Success_exam"].str.replace("No", "N")

df['Success_exam'] = df['Success_exam'].fillna('N')

df

avg_hours_attended = df['Hours_attended'].mean()

df['Hours_attended'] = df["Hours_attended"].fillna(avg_hours_attended)

df

    Gender   Courses  Hours_attended  Hours_prepared Success_exam
0     Male   Science            20.0             7.0            Y
1     Male  Commerce             4.0             4.0           No
2   Female   Science            28.0            14.0          Yes
3     Male      Arts            18.0             8.0          Yes
4     Male  Commerce            12.0             NaN            N
5   Female   Science            24.0            12.0          NaN
6   Female      Arts            26.0            11.0          Yes
7     Male  Commerce             8.0             3.0            N
8   Female   Science            25.0            14.0          Yes
9   Female      Arts            10.0             4.0            N
10    Male  Commerce             NaN            12.0          Yes
11  Female      Arts            12.0             8.0           No
12    Male      Arts            10.0             7.0            N
13  Female   Science            29.0             NaN            Y
14    Male   Science            30.0            14.0          Yes
15  Female  Commerce            22.0            11.0          Yes
16    Male   Science            27.0            15.0          NaN
17  Female      Arts            20.0            10.0            Y
18    Male  Commerce             9.0            12.0           No
19  Female   Science            25.0            14.0          Yes
20    Male      Arts            18.0             8.0          Yes
21  Female  Commerce           180.0            40.0          NaN

np.float64(557.0)

np.int64(0)

Gender            0
Courses           0
Hours_attended    1
Hours_prepared    2
Success_exam      3
dtype: int64

    Gender   Courses  Hours_attended  Hours_prepared Success_exam
0     Male   Science        20.00000             7.0            Y
1     Male  Commerce         4.00000             4.0            N
2   Female   Science        28.00000            14.0            Y
3     Male      Arts        18.00000             8.0            Y
4     Male  Commerce        12.00000             NaN            N
5   Female   Science        24.00000            12.0            N
6   Female      Arts        26.00000            11.0            Y
7     Male  Commerce         8.00000             3.0            N
8   Female   Science        25.00000            14.0            Y
9   Female      Arts        10.00000             4.0            N
10    Male  Commerce        26.52381            12.0            Y
11  Female      Arts        12.00000             8.0            N
12    Male      Arts        10.00000             7.0            N
13  Female   Science        29.00000             NaN            Y
14    Male   Science        30.00000            14.0            Y
15  Female  Commerce        22.00000            11.0            Y
16    Male   Science        27.00000            15.0            N
17  Female      Arts        20.00000            10.0            Y
18    Male  Commerce         9.00000            12.0            N
19  Female   Science        25.00000            14.0            Y
20    Male      Arts        18.00000             8.0            Y
21  Female  Commerce       180.00000            40.0            N