In [24]:
import pandas as pd

from IPython.display import display


# Series
[2, 4, 6, 8]

s = pd.Series([6, 9, 33])
print(s)

s2 = pd.Series(('Ade', 'Bimbo', 'Charles'), index=['a', 'b', 'c'])
print(s2)

s2['b']

0     6
1     9
2    33
dtype: int64
a        Ade
b      Bimbo
c    Charles
dtype: str

'Bimbo'

In [3]:
dict_data = {
    'Abdul': 19,
    'Giwa': 21
}

ser = pd.Series(dict_data)
ser['Abdul']

np.int64(19)

In [ ]:
s = pd.Series(100, index=list(range(4)))

s

0    100
1    100
2    100
3    100
dtype: int64

In [ ]:
# Create a Series containing:
# 50, 60, 70, 80
#  using indexes:
# Math, English, Physics, Chemistry

In [5]:
# Dataframes
data = {
    "Name": ["John", "Mary", "Steve"],
    "Age": [18, 17, 19],
    "Score": [85, 92, 76]
}

df = pd.DataFrame(data)

print(df)
display(df)

df.iloc[0]
# df.Score[1]
# df['Score'][1]
df['Score']

    Name  Age  Score
0   John   18     85
1   Mary   17     92
2  Steve   19     76

    Name  Age  Score
0   John   18     85
1   Mary   17     92
2  Steve   19     76

0    85
1    92
2    76
Name: Score, dtype: int64

In [ ]:
data = {
    "Richard": [
        ["M", "M"],
        ["Emy", "F"],
        ["Adam", "M"],
    ]
}

df = pd.DataFrame(data, columns=['Name', 'Gender'])

df['Name'][0]

'Richard'

In [36]:
_products = [
    {"id": 1, "name": "Laptop", "price": 1500.00, "color": 4281089616},
    {"id": 2, "name": "Smartphone", "price": 950.99, "color": 4281637083},
    {"id": 3, "name": "Tablet", "price": 599.99, "color": 4280193279},
    {"id": 4, "name": "Headphones", "price": 299.99, "color": 4293348412},
    {"id": 5, "name": "Smart Watch", "price": 399.99, "color": 4294928820},
]

products_data = {
    'id': [],
    'name': [],
    'price': []
}

for p in _products:
    products_data["id"].append(p["id"])
    products_data["name"].append(p["name"])
    products_data["price"].append(p["price"])


display(products_data)
df = pd.DataFrame(products_data)
df

{'id': [1, 2, 3, 4, 5],
 'name': ['Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Smart Watch'],
 'price': [1500.0, 950.99, 599.99, 299.99, 399.99]}

   id         name    price
0   1       Laptop  1500.00
1   2   Smartphone   950.99
2   3       Tablet   599.99
3   4   Headphones   299.99
4   5  Smart Watch   399.99

In [46]:
df = pd.read_csv('people-100.csv')

df.head(10)
df.tail()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [4]:
import pandas as pd

# Series

s = pd.Series(['a', 'b', 'c', 'd'])

print(s[3])

d

In [8]:
s = pd.Series(['Ade', 'Bob', 'Charles'], index=['x', 'y', 'z'])

s['y']

'Bob'

In [14]:
dt = {
    'name': 'Jumoke',
    'country': 'Canada',
    'height': 1.4
}

s = pd.Series(dt)

s['height']

1.4

In [16]:
pd.Series(range(5, 30, 5), index=range(5))

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [ ]:
# Dataframes: 2D
from IPython.display import display

pairs = [
    ['Ade', 20],
    ['Badero', 19],
    ['Chide', 21],
    ['Deede', 23],
]

df = pd.DataFrame(pairs, columns=['Name', 'Age'])

display(df)
print("-" * 15)
df['Name']
df.Age

df.iloc[1]['Age']

     Name  Age
0     Ade   20
1  Badero   19
2   Chide   21
3   Deede   23

---------------

Name    Badero
Age         19
Name: 1, dtype: object

In [ ]:
data = {
    "Name": ["John", "Mary", "Steve"],
    "Age": [18, 17, 19],
    "Score": [85, 92, 76]
}

df = pd.DataFrame(data)

df.sort_values('Age', ascending=True, axis=0)
# df[['Name']]

KeyError: 'Age'

In [ ]:
df = pd.read_csv('people-100.csv')

df.describe() #statistical overview of df

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [57]:
# Manipulating data

df = pd.read_csv('sales.csv')

display(df.head(3))
print('-' * 15)


product_price_df = df[['product', 'unit_price']]
display(product_price_df)
product_price_df.describe()
product_price_df.info()

   order_id        date  product  quantity  unit_price  discount_rate
0      1001  2024-01-05   Laptop         2      1200.0           0.10
1      1002  2024-01-08    Mouse        15        25.0           0.05
2      1003  2024-01-12  Monitor         5       350.0           0.15

---------------

       product  unit_price
0       Laptop      1200.0
1        Mouse        25.0
2      Monitor       350.0
3     Keyboard        85.0
4       Laptop      1200.0
5   Headphones       120.0
6    USB Cable         8.0
7      Monitor       350.0
8       Laptop      1200.0
9     Keyboard        85.0
10       Mouse        25.0
11  Headphones       120.0
12     Monitor       350.0
13         NaN      1200.0
14   USB Cable         8.0
15    Keyboard        85.0
16  Headphones       120.0
17       Mouse        25.0
18     Monitor       350.0
19      Laptop      1200.0

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     19 non-null     str
 1   unit_price  20 non-null     float64
dtypes: float64(1), str(1)
memory usage: 452.0 bytes

In [8]:
df = pd.read_csv("sales.csv")

head_df = df.head()
# print(head_df)

df = df[["product", "unit_price", 'quantity', 'discount_rate']]


df['is_expensive'] = df['unit_price'] > df['unit_price'].median()


# display(df.head())
# df['unit_price'] - 100

df['gross_price'] = df['unit_price'] * df['quantity']

# display(df.head())
# print('-' * 15)

df['discounted_price'] = df['gross_price'] - (df['gross_price'] * df['discount_rate'])

df.head()

# high_value_order: one where discounted price IS ABOVE 1000
# is_cheap
#  unit_price < 20
df['high_value_order'] = df['discounted_price'] > 1000
df['is_cheap'] = df['unit_price'] < 20
df


# dicsount_category:
#   No Discount WHERE discount rate == 0
#   Low Discount WHERE discount rate < 5%
#   Medium Discount WHERE rate > 5%
#  High Discount WHERE rate > 10%

# price_tier (based on unit price)
#   Cheap < 20
#   Mid-range 20-200
#  Expensive   > 200

# is_cheap
#  unit_price < 20

,product,unit_price,quantity,discount_rate,is_expensive,gross_price,discounted_price,high_value_order,is_cheap
0,Laptop,1200.0,2,0.10,True,2400.0,2160.00,True,False
1,Mouse,25.0,15,0.05,False,375.0,356.25,False,False
2,Monitor,350.0,5,0.15,True,1750.0,1487.50,True,False
3,Keyboard,85.0,8,0.08,False,680.0,625.60,False,False
4,Laptop,1200.0,3,0.12,True,3600.0,3168.00,True,False
5,Headphones,120.0,20,0.10,False,2400.0,2160.00,True,False
6,USB Cable,8.0,50,0.00,False,400.0,400.00,False,True
7,Monitor,350.0,4,0.20,True,1400.0,1120.00,True,False
8,Laptop,1200.0,1,0.05,True,1200.0,1140.00,True,False
9,Keyboard,85.0,12,0.10,False,1020.0,918.00,False,False
10,Mouse,25.0,25,0.08,False,625.0,575.00,False,False
11,Headphones,120.0,10,0.15,False,1200.0,1020.00,True,False
12,Monitor,350.0,3,0.10,True,1050.0,945.00,False,False
13,Laptop,1200.0,2,0.18,True,2400.0,1968.00,True,False
14,USB Cable,8.0,100,0.05,False,800.0,760.00,False,True
15,Keyboard,85.0,6,0.12,False,510.0,448.80,False,False
16,Headphones,120.0,8,0.20,False,960.0,768.00,False,False
17,Mouse,25.0,30,0.10,False,750.0,675.00,False,False
18,Monitor,350.0,2,0.25,True,700.0,525.00,False,False
19,Laptop,1200.0,4,0.15,True,4800.0,4080.00,True,False

Using the attached CSV file

Derive the following columns from the dataset:

1. Height_m — convert Height_cm to metres.


2. BMI — calculate from height and weight.


3. Weekly_Workout_Minutes — workouts per week × average workout minutes.


4. Weekly_Workout_Hours — convert weekly minutes to hours.

In [18]:
import pandas as pd
from IPython.display import display

df = pd.read_csv('fitness_activity.csv')

# display(df.head())


df['Height_m'] = df['Height_cm'] / 100

df['BMI'] = round((df.Weight_kg / (df.Height_m ** 2)), 2)
df["Weekly_Workout_Minutes"] = df['Workouts_Per_Week'] * df['Avg_Workout_Minutes']
df['Weekly_Workout_Hours'] = round((df['Weekly_Workout_Minutes'] / 60), 2)

display(df.sample(10))

df.to_csv('fitness_activity_update.csv', index=False)

,Student_ID,Student_Name,Age,Gender,Height_cm,Weight_kg,Workouts_Per_Week,Avg_Workout_Minutes,Avg_Daily_Steps_Thousands,Resting_Heart_Rate,Preferred_Activity,Height_m,BMI,Weekly_Workout_Minutes,Weekly_Workout_Hours
23,ST024,Henry Williams,29,Male,174,74,3,50,7.7,43,Running,1.74,24.44,150,2.50
14,ST015,Esther Danjuma,26,Female,167,66,3,50,7.6,43,Yoga,1.67,23.67,150,2.50
29,ST030,Ahmed Bello,32,Male,182,89,2,40,6.6,53,Basketball,1.82,26.87,80,1.33
13,ST014,David Chukwu,22,Male,172,70,2,40,6.8,41,Cycling,1.72,23.66,80,1.33
31,ST032,Franklin Cole,28,Male,176,77,4,55,8.0,44,Swimming,1.76,24.86,220,3.67
25,ST026,Chinedu Ani,26,Male,184,90,3,45,7.0,47,Gym,1.84,26.58,135,2.25
18,ST019,Maryam Sani,23,Female,157,54,3,45,7.1,38,Running,1.57,21.91,135,2.25
17,ST018,Victor Osei,31,Male,185,95,4,65,8.7,52,Swimming,1.85,27.76,260,4.33
11,ST012,Samuel Okoro,30,Male,183,92,3,45,7.3,51,Gym,1.83,27.47,135,2.25
45,ST046,Patrick Obi,31,Male,181,87,4,60,8.6,51,Gym,1.81,26.56,240,4.00

In [20]:
new_df = df[['BMI', 'Weekly_Workout_Hours']]

new_df.to_csv('fitness_activity_update.csv', index=False)

new_df.to_excel('data.xlsx', index=False)

In [27]:
# Applying arithmetic operations to columns
# add, sub, mul, div

data = {
    "Name": ["John", "Mary", "Steve"],
    "Age": [18, 17, 19],
    "Score": [25, 32, 36]
}

df = pd.DataFrame(data)

df.Score = df.Score.add(10)
# df.Score.sub(5)
# df.Score.mul(5)
# df.Score.div(5)

df

    Name  Age  Score
0   John   18     35
1   Mary   17     42
2  Steve   19     46

In [30]:
products_data = {
    'Name': ['Headphones', 'Shirt'],
    'Qty': [2, 3],
    'Price_$': [250.99, 25.75]
}

df = pd.DataFrame(products_data)

df["Price_₦"] = df['Price_$'].mul(1_390)

df

         Name  Qty  Price_$   Price_₦
0  Headphones    2   250.99  348876.1
1       Shirt    3    25.75   35792.5

In [40]:
s2 = pd.Series(("Bimbo", 'Abraham', 'abraham' ,"Charles"))

display(s2)
display(s2.sort_values(ascending=True))

s2

pd.Series([4, 2, 8, 5, 5, 9, 7]).sort_values(inplace=True)

0      Bimbo
1    Abraham
2    abraham
3    Charles
dtype: str

1    Abraham
0      Bimbo
3    Charles
2    abraham
dtype: str

1    2
0    4
3    5
4    5
6    7
2    8
5    9
dtype: int64

In [41]:
s2 = pd.Series(("Bimbo", "Abraham", "abraham", "Charles"))

display(s2)
display(s2.sort_values(ascending=True, inplace=True))


s2

0      Bimbo
1    Abraham
2    abraham
3    Charles
dtype: str

None

1    Abraham
0      Bimbo
3    Charles
2    abraham
dtype: str

In [48]:
products_data = {
    "Name": ["Headphones", "Shirt", 'Laptop'],
    "Qty": [2, 3, 0],
    "Price_$": [250.99, 25.75, 945.50],
}

df = pd.DataFrame(products_data)

df.sort_values("Price_$")
display(df.sort_values("Qty", inplace=False))

display(df)

         Name  Qty  Price_$
2      Laptop    0   945.50
0  Headphones    2   250.99
1       Shirt    3    25.75

         Name  Qty  Price_$
0  Headphones    2   250.99
1       Shirt    3    25.75
2      Laptop    0   945.50

In [ ]:
# loc vs iloc