In [ ]:
import pandas as pd

from IPython.display import display


# Series
[2, 4, 6, 8]

s = pd.Series([1, 2, 3])
print(s)

s2 = pd.Series(('Ade', 'Bimbo', 'Charles'), index=['a', 'b', 'c'])
print(s2)

s2['b']

0    1
1    2
2    3
dtype: int64
a        Ade
b      Bimbo
c    Charles
dtype: str

'Bimbo'

In [ ]:
dict_data = {
    'Abdul': 19,
    'Giwa': 21
}

ser = pd.Series(dict_data)
ser

Abdul    19
Giwa     21
dtype: int64

In [ ]:
s = pd.Series(100, index=list(range(4)))

s

0    100
1    100
2    100
3    100
dtype: int64

In [ ]:
# Create a Series containing:
# 50, 60, 70, 80
#  using indexes:
# Math, English, Physics, Chemistry

In [31]:
# Dataframes
data = {
    "Name": ["John", "Mary", "Steve"],
    "Age": [18, 17, 19],
    "Score": [85, 92, 76]
}

df = pd.DataFrame(data)

print(df)
display(df)

df.iloc[1]['Score']
df.Score[1]
df['Score'][1]

    Name  Age  Score
0   John   18     85
1   Mary   17     92
2  Steve   19     76

    Name  Age  Score
0   John   18     85
1   Mary   17     92
2  Steve   19     76

np.int64(92)

In [ ]:
data = {
    "Richard": [
        ["M", "M"],
        ["Emy", "F"],
        ["Adam", "M"],
    ]
}

df = pd.DataFrame(data, columns=['Name', 'Gender'])

df['Name'][0]

'Richard'

In [36]:
_products = [
    {"id": 1, "name": "Laptop", "price": 1500.00, "color": 4281089616},
    {"id": 2, "name": "Smartphone", "price": 950.99, "color": 4281637083},
    {"id": 3, "name": "Tablet", "price": 599.99, "color": 4280193279},
    {"id": 4, "name": "Headphones", "price": 299.99, "color": 4293348412},
    {"id": 5, "name": "Smart Watch", "price": 399.99, "color": 4294928820},
]

products_data = {
    'id': [],
    'name': [],
    'price': []
}

for p in _products:
    products_data["id"].append(p["id"])
    products_data["name"].append(p["name"])
    products_data["price"].append(p["price"])


display(products_data)
df = pd.DataFrame(products_data)
df

{'id': [1, 2, 3, 4, 5],
 'name': ['Laptop', 'Smartphone', 'Tablet', 'Headphones', 'Smart Watch'],
 'price': [1500.0, 950.99, 599.99, 299.99, 399.99]}

   id         name    price
0   1       Laptop  1500.00
1   2   Smartphone   950.99
2   3       Tablet   599.99
3   4   Headphones   299.99
4   5  Smart Watch   399.99

In [46]:
df = pd.read_csv('people-100.csv')

df.head(10)
df.tail()

,Index,User Id,First Name,Last Name,Sex,Email,Phone,Date of birth,Job Title
95,96,5eFda7caAeB260E,Dennis,Barnes,Female,bmartin@example.org,001-095-524-2112x257,1954-07-30,Software engineer
96,97,CCbFce93d3720bE,Steve,Patterson,Female,latasha46@example.net,001-865-478-5157,1932-04-29,Barrister
97,98,2fEc528aFAF0b69,Wesley,Bray,Male,regina11@example.org,995-542-3004x76800,1994-12-28,Police officer
98,99,Adc7ad9B6e4A1Fe,Summer,Oconnell,Female,alexiscantrell@example.org,001-273-685-6932x092,2012-04-12,Broadcast journalist
99,100,b8D0aD3490FC7e1,Mariah,Bernard,Male,pcopeland@example.org,(341)594-6554x44657,2016-11-15,IT sales professional

In [4]:
import pandas as pd

# Series

s = pd.Series(['a', 'b', 'c', 'd'])

print(s[3])

d

In [8]:
s = pd.Series(['Ade', 'Bob', 'Charles'], index=['x', 'y', 'z'])

s['y']

'Bob'

In [14]:
dt = {
    'name': 'Jumoke',
    'country': 'Canada',
    'height': 1.4
}

s = pd.Series(dt)

s['height']

1.4

In [16]:
pd.Series(range(5, 30, 5), index=range(5))

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [ ]:
# Dataframes: 2D
from IPython.display import display

pairs = [
    ['Ade', 20],
    ['Badero', 19],
    ['Chide', 21],
    ['Deede', 23],
]

df = pd.DataFrame(pairs, columns=['Name', 'Age'])

display(df)
print("-" * 15)
df['Name']
df.Age

df.iloc[1]['Age']

     Name  Age
0     Ade   20
1  Badero   19
2   Chide   21
3   Deede   23

---------------

Name    Badero
Age         19
Name: 1, dtype: object

In [ ]:
data = {
    "Name": ["John", "Mary", "Steve"],
    "Age": [18, 17, 19],
    "Score": [85, 92, 76]
}

df = pd.DataFrame(data)

df.sort_values('Age', ascending=True, axis=0)
# df[['Name']]

KeyError: 'Age'

In [ ]:
df = pd.read_csv('people-100.csv')

df.describe() #statistical overview of df

            Index
count  100.000000
mean    50.500000
std     29.011492
min      1.000000
25%     25.750000
50%     50.500000
75%     75.250000
max    100.000000

In [57]:
# Manipulating data

df = pd.read_csv('sales.csv')

display(df.head(3))
print('-' * 15)


product_price_df = df[['product', 'unit_price']]
display(product_price_df)
product_price_df.describe()
product_price_df.info()

   order_id        date  product  quantity  unit_price  discount_rate
0      1001  2024-01-05   Laptop         2      1200.0           0.10
1      1002  2024-01-08    Mouse        15        25.0           0.05
2      1003  2024-01-12  Monitor         5       350.0           0.15

---------------

       product  unit_price
0       Laptop      1200.0
1        Mouse        25.0
2      Monitor       350.0
3     Keyboard        85.0
4       Laptop      1200.0
5   Headphones       120.0
6    USB Cable         8.0
7      Monitor       350.0
8       Laptop      1200.0
9     Keyboard        85.0
10       Mouse        25.0
11  Headphones       120.0
12     Monitor       350.0
13         NaN      1200.0
14   USB Cable         8.0
15    Keyboard        85.0
16  Headphones       120.0
17       Mouse        25.0
18     Monitor       350.0
19      Laptop      1200.0

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 2 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   product     19 non-null     str
 1   unit_price  20 non-null     float64
dtypes: float64(1), str(1)
memory usage: 452.0 bytes

In [ ]:
df = pd.read_csv("sales.csv")

head_df = df.head()
print(head_df)

df = df[["product", "unit_price", 'quantity', 'discount_rate']]


df['is_expensive'] = df['unit_price'] > df['unit_price'].median()


# display(df.head())
# df['unit_price'] - 100

df['gross_price'] = df['unit_price'] * df['quantity']

display(df.head())
# print('-' * 15)

df['discounted_price'] = df['gross_price'] - (df['gross_price'] * df['discount_rate'])

df.head()

# high_value_order: one where discounted price IS ABOVE 1000
# is_cheap
#  unit_price < 20


# dicsount_category:
#   No Discount WHERE discount rate == 0
#   Low Discount WHERE discount rate < 5%
#   Medium Discount WHERE rate > 5%
#  High Discount WHERE rate > 10%

# price_tier (based on unit price)
#   Cheap < 20
#   Mid-range 20-200
#  Expensive   > 200

# is_cheap
#  unit_price < 20

   order_id        date   product  quantity  unit_price  discount_rate
0      1001  2024-01-05    Laptop         2      1200.0           0.10
1      1002  2024-01-08     Mouse        15        25.0           0.05
2      1003  2024-01-12   Monitor         5       350.0           0.15
3      1004  2024-01-15  Keyboard         8        85.0           0.08
4      1005  2024-01-18    Laptop         3      1200.0           0.12

    product  unit_price  quantity  discount_rate  is_expensive  gross_price
0    Laptop      1200.0         2           0.10          True       2400.0
1     Mouse        25.0        15           0.05         False        375.0
2   Monitor       350.0         5           0.15          True       1750.0
3  Keyboard        85.0         8           0.08         False        680.0
4    Laptop      1200.0         3           0.12          True       3600.0

---------------

,product,unit_price,quantity,discount_rate,is_expensive,gross_price,discounted_price
0,Laptop,1200.0,2,0.10,True,2400.0,2160.00
1,Mouse,25.0,15,0.05,False,375.0,356.25
2,Monitor,350.0,5,0.15,True,1750.0,1487.50
3,Keyboard,85.0,8,0.08,False,680.0,625.60
4,Laptop,1200.0,3,0.12,True,3600.0,3168.00