In [14]:
import pandas as pd

s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])

print(s[s > 10])
# print(s['b'])
# print(s)

b    20
c    30
dtype: int64

In [ ]:
scores = (40, 39, 71)

subject_series = pd.Series(scores, index=['Maths', 'F.Maths', 'Lit.'])

print(subject_series + 10)
# print(subject_series > 40)
# print(subject_series[subject_series > 40])
print(subject_series)

In [ ]:
data = {
    "names":  ["Ade", "Bolu", "Chris"],
    "ages": [10, 11, 10]
}

s = pd.Series(data)
# print(s)


student_data = {
    "Ade": 10,
    "Bolu": 11,
    "Chris": 11
}

student_series = pd.Series(student_data)
print(student_series >= 10)

In [ ]:
income_data = {
    "Jan": 1.5,
    'Feb': 1.3,
    'Mar': 1.55,
    'April': 1.65,
    'May': 1.68,
    'June': 1.99
}

profits = pd.Series(income_data)
print(profits.mean())
print(profits.sum())
print(profits)

In [ ]:
s = pd.Series(50, index=[1, 2, 3, 4])

print(s)

In [ ]:
data = {
    "name": ['Wu', 'Xi', 'Yuan', 'Zelda'],
    'age': (25, 25, 24, None)
}

df = pd.DataFrame(data, index=[1, 2, 3, 4])
# print(df)
# print("----")
# print(df['name'])
# print(df['age'])
print(df.iloc[3]['name'])

In [ ]:
student_data = [
    ("Ashera", 80.5),
    ("Bobola", 79),
    ['Cristiano', 5.0]
]

df = pd.DataFrame(student_data, columns=['Name', 'Score'])
print(df)

df.iloc[0]

In [ ]:
from IPython.display import display

import pandas as pd

df = pd.read_csv("users.csv")

# display(df.head(10))
# display(df.tail(2))

df.describe()
# df.shape
# df.info()


# df[['first_name', 'department']]

# df.loc[4:6]

       amount  fiscal_year  matriculation_year         phone       balance
count    14.0         14.0           14.000000  1.200000e+01     14.000000
mean   1000.0       2025.0         2014.142857  1.567314e+12   1200.000000
std       0.0          0.0            6.125070  1.152132e+12   7919.620232
min    1000.0       2025.0         2000.000000  7.033567e+09  -2000.000000
25%    1000.0       2025.0         2010.750000  7.850237e+09  -2000.000000
50%    1000.0       2025.0         2015.500000  2.347034e+12  -1000.000000
75%    1000.0       2025.0         2018.000000  2.347074e+12      0.000000
max    1000.0       2025.0         2022.000000  2.348135e+12  28250.000000

In [ ]:
import numpy as np

In [18]:
from IPython.display import display

data = {
    "name": ['Wu', 'Xi', 'Yuan', 'Zelda'],
    'age': (25, 25, None, None),
    'score': [90, 50, 60, 75]
}

df = pd.DataFrame(data)

df['gender'] = 'M'

df['dob'] = 2026 - df['age']

df['passed'] = df['score'] >= 55

df['score'].min()
# Create a column called Passed True/False if score >= 55
df.sort_values(by=['name'], ascending=False)

# df['age'] = df['age'].fillna(0)
df.loc[2, 'age'] = 20

print(df.isna())

df

    name    age  score  gender    dob  passed
0  False  False  False   False  False   False
1  False  False  False   False  False   False
2  False  False  False   False   True   False
3  False   True  False   False   True   False

    name   age  score gender     dob  passed
0     Wu  25.0     90      M  2001.0    True
1     Xi  25.0     50      M  2001.0   False
2   Yuan  20.0     60      M     NaN    True
3  Zelda   NaN     75      M     NaN    True

In [ ]:
df = pd.read_csv('users.csv')

# df[[''  'matric_number', 'department', 'email', ]]
display(df.head(5).sort_values(by='matriculation_year', ascending=False))
print('\n\n\n\n')
display(df.head(5))

In [5]:
import pandas as pd

df = pd.read_csv('students.csv')

df['Hobbies'] = df['Hobbies'].str.upper()
df['Gender'] = df['Gender'].str.replace('Male', 'M')
df["Gender"] = df["Gender"].str.replace("Female", "F")

# display(df)
df.isnull().sum()
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6    False
7    False
8    False
dtype: bool

In [17]:
display(df.head(3))
print("\n\n\n")
display(df.tail(4))

   Student_id    Name  Gender    Hobbies  C++ Marks  Java Marks  Python Marks
0         101  Oliver    Male    Dancing       67.0        86.0            98
1         103    Rita  Female    Singing        NaN        83.0            76
2         105   Smith    Male  Gardening       98.0        72.0            84

,Student_id,Name,Gender,Hobbies,C++ Marks,Java Marks,Python Marks
4,104,Richard,Male,Dancing,83.0,69.0,90
5,106,Linda,Female,Singing,75.0,88.0,87
6,107,Emy,Female,Photography,83.0,91.0,89
7,111,David,Male,Cooking,80.0,74.0,81

In [15]:
dancers = df[df['Hobbies'] == 'Dancing']

display(dancers)

   Student_id     Name Gender  Hobbies  C++ Marks  Java Marks  Python Marks
0         101   Oliver   Male  Dancing       67.0        86.0            98
4         104  Richard   Male  Dancing       83.0        69.0            90

In [27]:
missing_java = df[df['Java Marks'].isna()]

missing_java

   Student_id     Name Gender  Hobbies  C++ Marks  Java Marks  Python Marks
3         102  Michael   Male  Cooking       87.0         NaN            75

In [28]:
df.fillna(0, inplace=True)

df

,Student_id,Name,Gender,Hobbies,C++ Marks,Java Marks,Python Marks
0,101,Oliver,Male,Dancing,67.0,86.0,98
1,103,Rita,Female,Singing,0.0,83.0,76
2,105,Smith,Male,Gardening,98.0,72.0,84
3,102,Michael,Male,Cooking,87.0,0.0,75
4,104,Richard,Male,Dancing,83.0,69.0,90
5,106,Linda,Female,Singing,75.0,88.0,87
6,107,Emy,Female,Photography,83.0,91.0,89
7,111,David,Male,Cooking,80.0,74.0,81

In [39]:
df['Average'] = df[['C++ Marks', 'Java Marks', 'Python Marks']].mean(axis=1)

df

sorted_names_df = df.sort_values(by=['Name'], ascending=[True])

display(sorted_names_df)

print("\n\n\n\n")


sorted_averages_df = df.sort_values(by=["Average"], ascending=[False])
display(sorted_averages_df)

,Student_id,Name,Gender,Hobbies,C++ Marks,Java Marks,Python Marks,Average
7,111,David,Male,Cooking,80.0,74.0,81,78.333333
6,107,Emy,Female,Photography,83.0,91.0,89,87.666667
5,106,Linda,Female,Singing,75.0,88.0,87,83.333333
3,102,Michael,Male,Cooking,87.0,NaN,75,81.000000
0,101,Oliver,Male,Dancing,67.0,86.0,98,83.666667
4,104,Richard,Male,Dancing,83.0,69.0,90,80.666667
1,103,Rita,Female,Singing,NaN,83.0,76,79.500000
2,105,Smith,Male,Gardening,98.0,72.0,84,84.666667

,Student_id,Name,Gender,Hobbies,C++ Marks,Java Marks,Python Marks,Average
6,107,Emy,Female,Photography,83.0,91.0,89,87.666667
2,105,Smith,Male,Gardening,98.0,72.0,84,84.666667
0,101,Oliver,Male,Dancing,67.0,86.0,98,83.666667
5,106,Linda,Female,Singing,75.0,88.0,87,83.333333
3,102,Michael,Male,Cooking,87.0,NaN,75,81.000000
4,104,Richard,Male,Dancing,83.0,69.0,90,80.666667
1,103,Rita,Female,Singing,NaN,83.0,76,79.500000
7,111,David,Male,Cooking,80.0,74.0,81,78.333333